<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoAgentes.Application\AutoAgentes.Application.csproj" />
    <ProjectReference Include="..\AutoAgentes.App\AutoAgentes.App.csproj" />
    <ProjectReference Include="..\AutoAgentes.Contracts\AutoAgentes.Contracts.csproj" />
    <ProjectReference Include="..\AutoAgentes.Domain\AutoAgentes.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.64.0" />
  </ItemGroup>

</Project>